runtime: python39

env: standard

env_variables:
  GOOGLE_APPLICATION_CREDENTIALS: 'sonicseal.json'

handlers:
- url: /static
  static_dir: static

- url: /.*
  script: auto

automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: automatic  # default is automatic
  min_pending_latency: automatic  # default is 30ms
  max_pending_latency: automatic  # default is automatic

resources:
  cpu: 1
  memory_gb: 4
  disk_size_gb: 10
